services:
  backend:
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pdm_platform
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - NATS_URL=nats://nats:4222
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - ENVIRONMENT=development
